export const SET_BASE_LEVEL = 'SET_BASE_LEVEL';
export const SET_JOB_LEVEL = 'SET_JOB_LEVEL';
export const SET_JOB = 'SET_JOB';
export const SET_STAT = 'SET_STAT';
export const LOAD_SAVE_DATA = 'LOAD_SAVE_DATA';

export const UPDATE_ASPD_WEAPON_ID = 'UPDATE_ASPD_WEAPON_ID';
export const UPDATE_ASPD_LEFTHAND_ID = 'UPDATE_ASPD_LEFTHAND_ID';
export const UPDATE_ASPD_EQULTMENTS_ADDITION = 'UPDATE_ASPD_EQULTMENTS_ADDITION';
export const UPDATE_ASPD_SKILLS_ADDITION = 'UPDATE_ASPD_SKILLS_ADDITION';
export const UPDATE_ASPD_POTION_ADDITION = 'UPDATE_ASPD_POTION_ADDITION';
